name: tv
description: A new Flutter project.
publish_to: 'none'
version: 1.5.5+69

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sprintf: ^7.0.0
  graphql_flutter: ^5.1.2
  cupertino_icons: ^1.0.3
  intl: ^0.19.0
  font_awesome_flutter: ^10.1.0
  http: ^1.2.2
  localstorage: ^4.0.0+1
  share_plus: ^11.1.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.1.2
  mime: ^2.0.0
  video_player: ^2.9.1
  audioplayers: ^6.0.0
  chewie: ^1.2.2
  flutter_widget_from_html: ^0.16.1
  fluttertoast: ^8.0.7
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_remote_config: ^6.0.0
  firebase_analytics: ^12.0.0

  flutter_svg: ^2.0.0
  flutter_datetime_picker_plus: ^2.2.0
  webview_flutter: ^4.7.0
#  flutter_inappwebview: 6.1.0+1
  youtube_player_flutter: ^9.1.2

  visibility_detector: ^0.4.0+2
  auto_size_text: ^3.0.0
  photo_view: ^0.15.0
  get: ^4.6.6
  pdf_render: ^1.4.12
  app_tracking_transparency: ^2.0.6
  extended_text: ^15.0.2
  audio_session: ^0.2.2
  package_info_plus: ^8.3.1
  equatable: ^2.0.5
  youtube_explode_dart: ^2.0.2
  percent_indicator: ^4.2.3


  flutter_embedded_webview:
    git:
      url: https://github.com/mirror-media/flutter_embedded_webview.git
      ref: master

  real_time_invoice_widget:
    git:
      url: https://github.com/mirror-media/RealTimeInvoiceWidget.git
      ref: main

  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.3.2
  upgrader: ^11.5.0
  url_launcher: ^6.3.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: any
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/image/
    - assets/image/ombuds/
    - assets/image/search/
    - assets/image/election/
